### PR TITLE
fix: keep reactivity after hmr updates

### LINKED ISSUE #11: After hmr update, updates doesnt trigger rerender
Steps to reproduce:

1. Start server
2. click reactivue counter, it works
3. click react counter, it works
4. go back editor and just save file to trigger hmr
5. click reactivue counter, it doesnt rerender
6. click react counter, it triggers rerender and updates reactivue counter as you click

Code: Vite 2.0 react-ts template, same issue occurs on preact template too

```tsx
import React, { useState } from 'react'
import './App.css'
import { defineComponent, ref } from 'reactivue'

const Mouse = defineComponent(
  () => {
    const a = ref(0)
    const inc = () => a.value++
    return { inc, a }
  },
  ({ inc, a }) => {
    return (
      <div className="card" style={{marginBottom: '25px'}}>
        <p>reactivue counter</p>
        <button onClick={inc}>{a}</button>
      </div>
    )
  },
)

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <Mouse/>
      <div>
        react counter
      </div>
      <button onClick={() => setCount((count) => count + 1)}>
        count is: {count}
      </button>
    </div>
  )
}

export default App

```

### PR DESCRIPTION
**Pull request by sibbng**
Fix #11 

Not really a fix, actually it is a workaround.

I call it workaround, because it is works differently than vanilla React components.
Vanilla React components are keep states across HMR updates until you change initial state.

But with this PR, resets Reactivue state to its initial state after every HMR update. I think this is better than current behaviour. In current status, HMR updates completely killing reactivity until reloading page manually.

Also tested in Preact. Work as expected.

### CODE REVIEW

**Comment by crutchcorn** [comment]
I was hesitant on the initial revision of this change, but now that there's an instance check, I think this makes a lot of sense. 

Can we leave a comment in code explaining that this is for HMR?

**Comment by antfu** [comment]
Agree having some comments would be helpful.

**Comment by sibbng** [comment]
I'm working on a better solution which is invalidates setup values if they changed. I got it working. That means, it is an actual fix and act like real HMR. I will push it after clearing.

**Comment by sibbng** [comment]
Pushed 🎉

File: packages/reactivue/src/component.ts [hunk 1]
```diff
@@ -27,7 +27,9 @@ export const createNewInstanceWithId = (id: number, props: any, data: Ref<any> =
     props,
     data,
     isUnmounted: false,
+    willUnmount: false,
```
Comment (antfu) [inline packages/reactivue/src/component.ts:30]:
```suggestion
    isUnmounting: false,
```

File: packages/reactivue/src/useSetup.ts [hunk 2]
```diff
@@ -53,12 +91,18 @@ export function useSetup<State, Props = {}>(
...
-            invokeLifeCycle(LifecycleHooks.BEFORE_UPDATE)
-            // trigger React update
-            setTick(+new Date())
-            invokeLifeCycle(LifecycleHooks.UPDATED)
-          })
+          /**
+           * Prevent triggering rerender when component
+           * is about to unmount or really unmounted
+           */
+          if (!instance.willUnmount) {
```
Comment (antfu) [inline packages/reactivue/src/useSetup.ts:98]:
```suggestion
          if (instance.isUnmounting || instance.isUnmounted)
            return
```

Early return feels more intuitive here

File: packages/reactivue/src/useSetup.ts [hunk 3]
```diff
@@ -43,6 +49,38 @@ export function useSetup<State, Props = {}>(
 
   // trigger React re-render on data changes
   useEffect(() => {
+    /**
+     * Invalidate setup after hmr updates
+     */
+    if (process.env.NODE_ENV === 'development') {
+      let willCreateNewState = false
```
Comment (antfu) [inline packages/reactivue/src/useSetup.ts:56]:
```suggestion
      let isChanged = false
```

File: packages/reactivue/src/useSetup.ts [hunk 4]
```diff
@@ -43,6 +49,38 @@ export function useSetup<State, Props = {}>(
 
   // trigger React re-render on data changes
   useEffect(() => {
+    /**
+     * Invalidate setup after hmr updates
+     */
+    if (process.env.NODE_ENV === 'development') {
```
Comment (antfu) [inline packages/reactivue/src/useSetup.ts:55]: We could make this check outside of `useEffect`

File: packages/reactivue/src/useSetup.ts [hunk 5]
```diff
@@ -1,32 +1,38 @@
...
     useInstanceScope(id, () => {
-      const data = ref(setupFunction(readonly(props)))
+      const setupState = setupFunction(readonly(props))
+      const data = ref(setupState)
 
       invokeLifeCycle(LifecycleHooks.BEFORE_MOUNT)
 
       instance.data = data
+
+      for (const key of Object.keys(setupState))
```
Comment (antfu) [inline packages/reactivue/src/useSetup.ts:27]: Wrapper this with env development

File: packages/reactivue/src/useSetup.ts (hunk 4 above)
Comment (antfu) [reply packages/reactivue/src/useSetup.ts:55]: And we shall have a safe `typeof process !== 'undefined' && process.env.NODE_ENV` check.

**Review by antfu — COMMENTED** [review]
Looks good, just a few naming and styling changes.

File: packages/reactivue/src/useSetup.ts (hunk 2 above)
Comment (sibbng) [reply packages/reactivue/src/useSetup.ts:98]: `instance.isUnmounted` unnecessary in here. All effects will be cleared before this value become true. 

Probably you added this because of _"or really unmounted"_ comment. I mean here is the components removed by a value. {{show && <Comp />}}. That will be really unmounting component if show variable is falsy. But its reactivity effects will be alive, because we postponed removing effects in development.

**Comment by antfu** [comment]
Nice, thanks!
